name: 'Create a repository'
description: 'Creates a repository based on a template'
author: 'Spike Washburn'
inputs:
  repo-name:
    description: 'New repository name'
    required: true
  github-token:
    description: 'Token with permission to create repositories'
    required: true
  repo-org:
    description: 'Name of the organization the repository will be created in'
outputs:
  repo-url:
    description: 'URL of the created repository'
  git-url:
    description: 'GIT url of the created repository'
runs:
  using: 'node16'
  main: 'dist/index.js'
