name: 'build-test'
on:
  pull_request:

jobs:
  test: # test the action locally
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-name: create-repo-test
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          # repo-org: acme
